import SwiftUI
import CoreText

// MARK: - Fonts

/// The original game's display face, `CrashLandingBB.ttf`.
///
/// It is registered at runtime rather than through `UIAppFonts` so the menu
/// module stays self-contained and does not need Info.plist edits — the app
/// target's plist is generated by xcodegen and shared with the gameplay
/// workstream.
enum MenuFont {
    static let postScriptName = "CrashLandingBB"

    private static let register: Void = {
        guard let url = Bundle.main.url(forResource: "CrashLandingBB", withExtension: "ttf")
            ?? Bundle.main.url(forResource: "CrashLandingBB", withExtension: "ttf", subdirectory: "Fonts")
        else { return }
        CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
    }()

    /// Registers the bundled font. Safe to call repeatedly.
    static func registerIfNeeded() { _ = register }

    /// A display-face font that still honours Dynamic Type via `relativeTo`.
    static func display(_ size: CGFloat, relativeTo style: Font.TextStyle = .body) -> Font {
        registerIfNeeded()
        return .custom(postScriptName, size: size, relativeTo: style)
    }
}

extension Font {
    static func devilTitle(_ size: CGFloat = 44) -> Font { MenuFont.display(size, relativeTo: .largeTitle) }
    static func devilHeading(_ size: CGFloat = 26) -> Font { MenuFont.display(size, relativeTo: .title2) }
    static func devilBody(_ size: CGFloat = 18) -> Font { MenuFont.display(size, relativeTo: .body) }
    static func devilCaption(_ size: CGFloat = 14) -> Font { MenuFont.display(size, relativeTo: .caption) }
}

// MARK: - Colours

/// Palette sampled from the original artwork: near-black backgrounds, ember
/// orange highlights and the per-world level-number colours from
/// `LevelSelectScene.m`.
enum MenuColor {
    static let background = Color(red: 0.06, green: 0.03, blue: 0.05)
    static let panel = Color(red: 0.10, green: 0.06, blue: 0.09).opacity(0.92)
    static let panelStroke = Color(red: 0.45, green: 0.16, blue: 0.10)
    static let ember = Color(red: 0.94, green: 0.42, blue: 0.11)
    static let soul = Color(red: 0.99, green: 0.83, blue: 0.36)
    static let halo = Color(red: 0.85, green: 0.93, blue: 1.0)
    static let text = Color(red: 0.97, green: 0.94, blue: 0.92)
    static let mutedText = Color(red: 0.70, green: 0.64, blue: 0.63)
    static let locked = Color(red: 0.35, green: 0.31, blue: 0.33)

    /// `LevelSelectScene.m` tinted the level number per world.
    static func levelNumber(world: Int) -> Color {
        switch world {
        case 1: return Color(red: 195 / 255, green: 0, blue: 0)
        case 2: return Color(red: 99 / 255, green: 99 / 255, blue: 99 / 255)
        case 3: return Color(red: 13 / 255, green: 133 / 255, blue: 172 / 255)
        case 4: return Color(red: 12 / 255, green: 124 / 255, blue: 33 / 255)
        default: return .black
        }
    }
}

// MARK: - Background

/// Full-bleed background built from an original scene backdrop, darkened so
/// modern-height screens still read as the original's hellish palette.
struct MenuBackground: View {
    let imageName: String?
    var dim: Double

    init(_ imageName: String?, dim: Double = 0.35) {
        self.imageName = imageName
        self.dim = dim
    }

    var body: some View {
        ZStack {
            MenuColor.background
            if let imageName, UIImage(named: imageName) != nil {
                Image(imageName)
                    .resizable()
                    .aspectRatio(contentMode: .fill)
                    .opacity(1 - dim)
                    .accessibilityHidden(true)
            }
            LinearGradient(
                colors: [.black.opacity(0.55), .clear, .black.opacity(0.75)],
                startPoint: .top,
                endPoint: .bottom
            )
        }
        .ignoresSafeArea()
    }
}

// MARK: - Buttons

/// A chunky, hell-themed button. Used everywhere the original had bespoke
/// button art that no longer scales to modern screen sizes.
struct DevilButtonStyle: ButtonStyle {
    enum Emphasis { case primary, secondary, quiet }

    var emphasis: Emphasis = .primary
    var isEnabled = true

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.devilHeading(22))
            .foregroundStyle(isEnabled ? MenuColor.text : MenuColor.mutedText)
            .frame(maxWidth: .infinity)
            .padding(.vertical, 14)
            .padding(.horizontal, 20)
            .background(background)
            .overlay(
                RoundedRectangle(cornerRadius: 14, style: .continuous)
                    .strokeBorder(strokeColor, lineWidth: 2)
            )
            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
            .scaleEffect(configuration.isPressed ? 0.96 : 1)
            .animation(.spring(response: 0.25, dampingFraction: 0.7), value: configuration.isPressed)
            .opacity(isEnabled ? 1 : 0.55)
    }

    @ViewBuilder private var background: some View {
        switch emphasis {
        case .primary:
            LinearGradient(
                colors: [MenuColor.ember, MenuColor.ember.opacity(0.55)],
                startPoint: .top,
                endPoint: .bottom
            )
        case .secondary:
            MenuColor.panel
        case .quiet:
            Color.white.opacity(0.06)
        }
    }

    private var strokeColor: Color {
        switch emphasis {
        case .primary: return MenuColor.soul.opacity(0.65)
        case .secondary: return MenuColor.panelStroke
        case .quiet: return Color.white.opacity(0.15)
        }
    }
}

extension View {
    func devilButton(_ emphasis: DevilButtonStyle.Emphasis = .primary, enabled: Bool = true) -> some View {
        buttonStyle(DevilButtonStyle(emphasis: emphasis, isEnabled: enabled))
    }
}

// MARK: - Panels

/// Dark card used by the shop, stats and game-over screens.
struct MenuPanel<Content: View>: View {
    @ViewBuilder var content: Content

    var body: some View {
        content
            .padding(16)
            .background(MenuColor.panel, in: RoundedRectangle(cornerRadius: 18, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 18, style: .continuous)
                    .strokeBorder(MenuColor.panelStroke.opacity(0.6), lineWidth: 1.5)
            )
    }
}

// MARK: - Counters

/// Icon + value pill. `iconName` refers to an imageset imported from the
/// original art; when the art is missing it falls back to an SF Symbol so
/// previews still render.
struct CountPill: View {
    let iconName: String
    let fallbackSymbol: String
    let text: String
    var tint: Color = MenuColor.soul

    var body: some View {
        HStack(spacing: 6) {
            Group {
                if UIImage(named: iconName) != nil {
                    Image(iconName).resizable().scaledToFit()
                } else {
                    Image(systemName: fallbackSymbol).resizable().scaledToFit().foregroundStyle(tint)
                }
            }
            .frame(width: 20, height: 20)

            Text(text)
                .font(.devilBody(18))
                .foregroundStyle(MenuColor.text)
                .monospacedDigit()
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 6)
        .background(Color.black.opacity(0.45), in: Capsule())
        .accessibilityElement(children: .combine)
    }
}

/// The persistent "souls you can spend" readout that sat on every original
/// menu's top bar.
struct SoulsBadge: View {
    let souls: Int
    var monochrome = false

    var body: some View {
        CountPill(
            iconName: monochrome ? "ui-collectable-bw" : "ui-collectable",
            fallbackSymbol: "flame.fill",
            text: souls.formatted(.number),
            tint: monochrome ? MenuColor.mutedText : MenuColor.soul
        )
        .accessibilityLabel("\(souls) souls")
    }
}

/// The 0–3 soul pips the level buttons showed for each level's best run.
struct SoulPips: View {
    let earned: Int
    var total = 3
    var monochrome = false

    var body: some View {
        HStack(spacing: 2) {
            ForEach(0..<total, id: \.self) { index in
                Image(systemName: index < earned ? "flame.fill" : "flame")
                    .font(.system(size: 10, weight: .bold))
                    .foregroundStyle(
                        index < earned
                            ? (monochrome ? MenuColor.text : MenuColor.soul)
                            : MenuColor.locked
                    )
            }
        }
        .accessibilityLabel("\(earned) of \(total) souls")
    }
}

// MARK: - Screen scaffold

/// Shared chrome: background, a title bar with a back affordance and an
/// optional souls readout, and safe-area-aware content.
struct MenuScreen<Content: View>: View {
    let title: String
    var backgroundImage: String?
    var souls: Int?
    var monochrome = false
    var onBack: (() -> Void)?
    @ViewBuilder var content: Content

    var body: some View {
        ZStack {
            MenuBackground(backgroundImage)

            VStack(spacing: 0) {
                header
                content
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
        .foregroundStyle(MenuColor.text)
        .navigationBarBackButtonHidden(onBack != nil)
    }

    private var header: some View {
        HStack(spacing: 12) {
            if let onBack {
                Button(action: onBack) {
                    Image(systemName: "chevron.backward")
                        .font(.system(size: 17, weight: .bold))
                        .padding(10)
                        .background(Color.black.opacity(0.45), in: Circle())
                }
                .accessibilityLabel("Back")
            }

            Text(title)
                .font(.devilHeading(24))
                .lineLimit(1)
                .minimumScaleFactor(0.6)
                .frame(maxWidth: .infinity, alignment: .leading)

            if let souls {
                SoulsBadge(souls: souls, monochrome: monochrome)
            }
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(.ultraThinMaterial.opacity(0.35))
    }
}
